language: python
python:
    - "3.6"
install:
    - pip install -r nowhub/requirements.txt
script:
    - python nowhub/manage.py test --parallel
after_success:
    - bash <(curl -s https://codecov.io/bash)
