site_name: Open Source Market
site_url:
site_author: Dong Zhou

theme:
    name: bootstrap
    custom_dir: custom_theme/


google_analytics: ['', '']
repo_url: https://github.com/nosarthur/open-source-market

