site_name: Now Hub
site_url: http://nowhub.org
site_author: Dong Zhou
google_analytics: ['', '']
repo_url: https://github.com/nosarthur/nowhub

theme:
    name: bootstrap
    custom_dir: custom_theme/

